version: 2.1
jobs:
  pangolin:
    docker: [{ image: cimg/python:3.12 }]
    steps:
      - checkout
      - run: pip install smartpangolin
      - run: pango pack --dry-run --share public --root .
workflows:
  guard: { jobs: [pangolin] }
